ams/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('registration.urls')),
    path('', include('application_management.urls')),

    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

application_management/urls.py
from django.urls import path
from . import views


app_name = 'appmanage'
urlpatterns = [
    path('application-announcement/', views.application_announcement_view, name='app_announce'),
    path('application-announcement/new-round', views.announce_new_application_round_view, name='new_round'),

    path('application-form/<int:application_round_id>', views.application_form_view, name='application_form'),
    path('application-round/<int:application_round_id>/edit', views.application_round_edit_view, name='edit_application_round'),

    path('upload/', views.image_upload_view, name='upload_image'),

]

templates/application-announcement/announce-new-application-round.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Admin</title>
    <style>
        .style-form{margin-top: 20px; margin-left: 30px;}
        .style-button{margin-left: 100px;}
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <img class="navbar-brand" src="https://images-ext-2.discordapp.net/external/v8GEwxpOUsobq20sy2aTf4kOwD2R37nTWEZL3Y44jmo/%3F_nc_cat%3D107%26ccb%3D1-5%26_nc_sid%3D5cd70e%26_nc_eui2%3DAeFXSVX47nvaHsLl-NhSgwlq6u5Wj_l_Wi7q7laP-X9aLuZHUCo03XpmYI3zhoGv-EcEvRa5ZNuyDf-W6MHm7MaT%26_nc_ohc%3DikqO-rEXfX8AX9yuYQP%26_nc_ht%3Dscontent.fkkc1-1.fna%26oh%3D00_AT_2jPTizOukMAgOg5GsauXvT6VWXcEI5BsC7-DiceQMng%26oe%3D622B7E75/https/scontent.fkkc1-1.fna.fbcdn.net/v/t39.30808-6/275423173_4855741387855032_5796922971706807414_n.jpg" width="100" height="40" alt="CP : COLLEGE OF COMPUTING"/>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
        </div>
      </nav>
    <form class= "style-form" action="" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}       
        <button type="submit" class="btn btn-success">สร้าง</button>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <a href="/application-announcement" class="btn btn-danger">ยกเลิก</a>
    </form>

</body>
</html>

templates/application-announcement/announce.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>การรับสมัครนักศึกษาเข้าเรียน</title>
    <style>
      .nav-link{margin-left: 780px;}
      .bg-color{background-color: #99CCFF;}
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <img class="navbar-brand" src="https://images-ext-2.discordapp.net/external/v8GEwxpOUsobq20sy2aTf4kOwD2R37nTWEZL3Y44jmo/%3F_nc_cat%3D107%26ccb%3D1-5%26_nc_sid%3D5cd70e%26_nc_eui2%3DAeFXSVX47nvaHsLl-NhSgwlq6u5Wj_l_Wi7q7laP-X9aLuZHUCo03XpmYI3zhoGv-EcEvRa5ZNuyDf-W6MHm7MaT%26_nc_ohc%3DikqO-rEXfX8AX9yuYQP%26_nc_ht%3Dscontent.fkkc1-1.fna%26oh%3D00_AT_2jPTizOukMAgOg5GsauXvT6VWXcEI5BsC7-DiceQMng%26oe%3D622B7E75/https/scontent.fkkc1-1.fna.fbcdn.net/v/t39.30808-6/275423173_4855741387855032_5796922971706807414_n.jpg" 
      width="100" height="40" alt="CP : COLLEGE OF COMPUTING"/>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if  user.is_superuser %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'appmanage:new_round' %}">สร้างโครงการรับสมัครนักศึกษาเข้าเรียน</a>
          </li>
          
        </ul>
      </div>
      {% endif %}
    </div>
  </nav>
    {% if  user.is_superuser %}
        
        <table class="table" >
          <thead class="bg-color">
            <tr>
              <th scope="col">การรับสมัครเข้าศึกษา</th>
              <th scope="col">วันที่เริ่มสมัคร</th>
              <th scope="col">วันที่สิ้นสุดการสมัคร</th>

            </tr>
          </thead>

          <tbody>
            {% for round in application_round_list %}
                <tr>
                  <th scope="row" > <a href="{% url 'appmanage:edit_application_round' round.id %}"> {{ round.title }}</a> </th>
                  <td>{{ round.start_date }}</td>
                  <td>{{ round.end_date }}</td>
                </tr>

            {% endfor %}


          </tbody>
        </table>
    {% else %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">การรับสมัครเข้าศึกษา</th>
              <th scope="col">วันที่เริ่มสมัคร</th>
              <th scope="col">วันที่สิ้นสุดการสมัคร</th>

            </tr>
          </thead>

          <tbody>
            {% for round in application_round_list %}
                {% if round.visible and round.active %}
                <tr>
                  <th scope="row" > <a href="{% url 'appmanage:application_form' round.id %}"> {{ round.title }}</a> </th>
                  <td>{{ round.start_date }}</td>
                  <td>{{ round.end_date }}</td>

                </tr>
                {% endif %}
            {% endfor %}

          </tbody>
    {% endif %}

</body>
</html>

templates/application-announcement/application-form.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>User</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <style>
    .nav-link {
      margin-left: 610px;
    }

    .bg-color {
      background-color: #99CCFF;
    }

    form {
      margin: 30px;

    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <img class="navbar-brand"
        src="https://scontent.fkkc1-1.fna.fbcdn.net/v/t39.30808-6/275423173_4855741387855032_5796922971706807414_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=5cd70e&_nc_eui2=AeFXSVX47nvaHsLl-NhSgwlq6u5Wj_l_Wi7q7laP-X9aLuZHUCo03XpmYI3zhoGv-EcEvRa5ZNuyDf-W6MHm7MaT&_nc_ohc=ikqO-rEXfX8AX9yuYQP&_nc_ht=scontent.fkkc1-1.fna&oh=00_AT_2jPTizOukMAgOg5GsauXvT6VWXcEI5BsC7-DiceQMng&oe=622B7E75"
        alt="CP : COLLEGE OF COMPUTING" width="100"/>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_superuser %}
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page"
              href="{% url 'appmanage:new_round' %}">สร้างโครงการรับสมัครนักศึกษาเข้าเรียน</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
  </nav>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">ส่งเอกสาร</button>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href="/application-announcement" class="btn btn-danger">ยกเลิก</a>
  </form>


</body>

</html>

templates/application-announcement/application-round-edit-view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Admin</title>
    <style>
        .style-form{margin-top: 20px; margin-left: 30px;}
        .style-button{margin-left: 100px;}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <img class="navbar-brand" src="https://images-ext-2.discordapp.net/external/v8GEwxpOUsobq20sy2aTf4kOwD2R37nTWEZL3Y44jmo/%3F_nc_cat%3D107%26ccb%3D1-5%26_nc_sid%3D5cd70e%26_nc_eui2%3DAeFXSVX47nvaHsLl-NhSgwlq6u5Wj_l_Wi7q7laP-X9aLuZHUCo03XpmYI3zhoGv-EcEvRa5ZNuyDf-W6MHm7MaT%26_nc_ohc%3DikqO-rEXfX8AX9yuYQP%26_nc_ht%3Dscontent.fkkc1-1.fna%26oh%3D00_AT_2jPTizOukMAgOg5GsauXvT6VWXcEI5BsC7-DiceQMng%26oe%3D622B7E75/https/scontent.fkkc1-1.fna.fbcdn.net/v/t39.30808-6/275423173_4855741387855032_5796922971706807414_n.jpg" width="100" height="40" alt="CP : COLLEGE OF COMPUTING"/>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
        </div>
      </nav>
    <form class= "style-form" action="" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">บันทึก</button>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <a href="/application-announcement" class="btn btn-danger">ยกเลิก</a>
        
    </form>

</body>
</html>